name: Generate docs

on:
  push:
    branches: ["main"]
    paths:
      - lib/*.js
      - README.md

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        run: npm ci
      - name: Generate docs
        run: npm run doc
      - name: Commit and push
        run: |
          git config --global user.email "jjmerelo@gmail.com"
          git config --global user.name "AISstreamer Doc Bot"
          git commit -am ":robot: :memo:"
          git push
