name: Test and generate docs

on:
  push:
    branches: ["main"]
    paths:
      - lib/*.js
      - tests/*.js
      - README.md
      - .github/workflows/test-and-gen-docs.yml

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install modules
        run: npm ci
      - name: Test
        run: npm test
      - name: Generate docs
        run: npm run doc
      - name: Commit and push
        run: |
          git config --global user.email "jjmerelo@gmail.com"
          git config --global user.name "AISstreamer Doc Bot"
          git commit -am ":robot: :memo:"
          git push
